<?php

declare(strict_types=1);

// One-shot bootstrap: writes the email.ai.* sub-array into every non-English locale file.
// Run from project root: php tools/translate-ai-keys.php
// Re-runnable. Existing keys are preserved; only the email.ai sub-array is overwritten.

$translations = [
    'am' => [
        'heading' => 'የAI ጥቆማ',
        'footnote_prefix' => 'በ',
        'disclaimer' => 'በAI የተፈጠረ። ከመተግበርዎ በፊት ያረጋግጡ።',
        'cached_badge' => 'ካሽ የተደረገ',
        'failed_prefix' => 'የAI ትንተና አልተሳካም',
        'skipped_prefix' => 'የAI ትንተና ተዘሏል',
        'reason' => [
            'timeout' => 'ጊዜ አልፏል',
            'authentication_failed' => 'ማረጋገጫ አልተሳካም',
            'rate_limited' => 'መጠን ተገድቧል',
            'quota_exceeded' => 'ኮታ አልፏል',
            'unknown_error' => 'ያልታወቀ ስህተት',
            'output_rejected_matched_injection_marker' => 'ውጤት ውድቅ ተደርጓል (የመርፌ ምልክት)',
            'hourly_cap_reached' => 'የሰዓት ገደብ ደርሷል',
            'circuit_open' => 'ወረዳ ክፍት',
        ],
    ],
    'ar' => [
        'heading' => 'اقتراح الذكاء الاصطناعي',
        'footnote_prefix' => 'عبر',
        'disclaimer' => 'مُولَّد بالذكاء الاصطناعي. تحقق قبل التنفيذ.',
        'cached_badge' => 'مخزن مؤقتاً',
        'failed_prefix' => 'فشل تحليل الذكاء الاصطناعي',
        'skipped_prefix' => 'تم تخطي تحليل الذكاء الاصطناعي',
        'reason' => [
            'timeout' => 'انتهت المهلة',
            'authentication_failed' => 'فشل التحقق',
            'rate_limited' => 'تم تقييد المعدل',
            'quota_exceeded' => 'تم تجاوز الحصة',
            'unknown_error' => 'خطأ غير معروف',
            'output_rejected_matched_injection_marker' => 'تم رفض المخرجات (علامة حقن)',
            'hourly_cap_reached' => 'تم بلوغ الحد الساعي',
            'circuit_open' => 'الدائرة مفتوحة',
        ],
    ],
    'az' => [
        'heading' => 'AI Təklifi',
        'footnote_prefix' => 'vasitəsilə',
        'disclaimer' => 'AI tərəfindən yaradılıb. Tətbiq etməzdən əvvəl yoxlayın.',
        'cached_badge' => 'keşlənmiş',
        'failed_prefix' => 'AI təhlili uğursuz oldu',
        'skipped_prefix' => 'AI təhlili atlandı',
        'reason' => [
            'timeout' => 'vaxt bitdi',
            'authentication_failed' => 'kimlik doğrulama uğursuz',
            'rate_limited' => 'sürət məhdudlaşdırılıb',
            'quota_exceeded' => 'kvota aşıldı',
            'unknown_error' => 'naməlum xəta',
            'output_rejected_matched_injection_marker' => 'çıxış rədd edildi (injeksiya işarəsi)',
            'hourly_cap_reached' => 'saatlıq həddə çatıldı',
            'circuit_open' => 'dövrə açıq',
        ],
    ],
    'bg' => [
        'heading' => 'AI предложение',
        'footnote_prefix' => 'чрез',
        'disclaimer' => 'Генерирано от AI. Проверете, преди да действате.',
        'cached_badge' => 'кеширано',
        'failed_prefix' => 'AI анализът е неуспешен',
        'skipped_prefix' => 'AI анализът е пропуснат',
        'reason' => [
            'timeout' => 'изтекло време',
            'authentication_failed' => 'неуспешна автентикация',
            'rate_limited' => 'ограничена честота',
            'quota_exceeded' => 'превишена квота',
            'unknown_error' => 'неизвестна грешка',
            'output_rejected_matched_injection_marker' => 'изходът е отхвърлен (маркер за инжекция)',
            'hourly_cap_reached' => 'достигнат часов лимит',
            'circuit_open' => 'веригата е отворена',
        ],
    ],
    'bn' => [
        'heading' => 'AI পরামর্শ',
        'footnote_prefix' => 'মাধ্যমে',
        'disclaimer' => 'AI দ্বারা তৈরি। কাজ করার আগে যাচাই করুন।',
        'cached_badge' => 'ক্যাশ করা',
        'failed_prefix' => 'AI বিশ্লেষণ ব্যর্থ',
        'skipped_prefix' => 'AI বিশ্লেষণ এড়ানো হয়েছে',
        'reason' => [
            'timeout' => 'সময় শেষ',
            'authentication_failed' => 'প্রমাণীকরণ ব্যর্থ',
            'rate_limited' => 'হার সীমিত',
            'quota_exceeded' => 'কোটা অতিক্রান্ত',
            'unknown_error' => 'অজানা ত্রুটি',
            'output_rejected_matched_injection_marker' => 'আউটপুট প্রত্যাখ্যাত (ইনজেকশন চিহ্ন)',
            'hourly_cap_reached' => 'ঘণ্টার সীমায় পৌঁছেছে',
            'circuit_open' => 'সার্কিট খোলা',
        ],
    ],
    'bs' => [
        'heading' => 'AI prijedlog',
        'footnote_prefix' => 'putem',
        'disclaimer' => 'Generirano AI-om. Provjerite prije primjene.',
        'cached_badge' => 'keširano',
        'failed_prefix' => 'AI analiza neuspjela',
        'skipped_prefix' => 'AI analiza preskočena',
        'reason' => [
            'timeout' => 'isteklo vrijeme',
            'authentication_failed' => 'neuspjela autentifikacija',
            'rate_limited' => 'ograničena učestalost',
            'quota_exceeded' => 'prekoračena kvota',
            'unknown_error' => 'nepoznata greška',
            'output_rejected_matched_injection_marker' => 'izlaz odbijen (oznaka injekcije)',
            'hourly_cap_reached' => 'dosegnut satni limit',
            'circuit_open' => 'krug otvoren',
        ],
    ],
    'ca' => [
        'heading' => 'Suggeriment de l\'IA',
        'footnote_prefix' => 'via',
        'disclaimer' => 'Generat per IA. Verifica abans d\'actuar.',
        'cached_badge' => 'en memòria cau',
        'failed_prefix' => 'Anàlisi d\'IA fallida',
        'skipped_prefix' => 'Anàlisi d\'IA omesa',
        'reason' => [
            'timeout' => 'temps esgotat',
            'authentication_failed' => 'autenticació fallida',
            'rate_limited' => 'taxa limitada',
            'quota_exceeded' => 'quota superada',
            'unknown_error' => 'error desconegut',
            'output_rejected_matched_injection_marker' => 'sortida rebutjada (marcador d\'injecció)',
            'hourly_cap_reached' => 'límit per hora assolit',
            'circuit_open' => 'circuit obert',
        ],
    ],
    'ckb' => [
        'heading' => 'پێشنیاری AI',
        'footnote_prefix' => 'لەڕێگەی',
        'disclaimer' => 'بە AI دروستکراوە. پێش کارپێکردن پشتڕاست بکەرەوە.',
        'cached_badge' => 'کاش کراو',
        'failed_prefix' => 'شیکاری AI سەرکەوتوو نەبوو',
        'skipped_prefix' => 'شیکاری AI تێپەڕێنرا',
        'reason' => [
            'timeout' => 'کاتی تەواوبوو',
            'authentication_failed' => 'پشتڕاستکردنەوە سەرکەوتوو نەبوو',
            'rate_limited' => 'ڕێژە سنووردارکراوە',
            'quota_exceeded' => 'کۆتا تێپەڕاند',
            'unknown_error' => 'هەڵەی نەناسراو',
            'output_rejected_matched_injection_marker' => 'دەرئەنجام ڕەتکرایەوە (نیشانەی دەرزی)',
            'hourly_cap_reached' => 'سنووری کاتژمێر گەیشت',
            'circuit_open' => 'بازنە کراوەیە',
        ],
    ],
    'cs' => [
        'heading' => 'Návrh AI',
        'footnote_prefix' => 'přes',
        'disclaimer' => 'Vygenerováno AI. Před použitím ověřte.',
        'cached_badge' => 'z cache',
        'failed_prefix' => 'Analýza AI selhala',
        'skipped_prefix' => 'Analýza AI přeskočena',
        'reason' => [
            'timeout' => 'vypršel časový limit',
            'authentication_failed' => 'autentizace selhala',
            'rate_limited' => 'omezená frekvence',
            'quota_exceeded' => 'překročena kvóta',
            'unknown_error' => 'neznámá chyba',
            'output_rejected_matched_injection_marker' => 'výstup zamítnut (značka injekce)',
            'hourly_cap_reached' => 'dosažen hodinový limit',
            'circuit_open' => 'okruh otevřen',
        ],
    ],
    'da' => [
        'heading' => 'AI-forslag',
        'footnote_prefix' => 'via',
        'disclaimer' => 'AI-genereret. Bekræft før handling.',
        'cached_badge' => 'cachet',
        'failed_prefix' => 'AI-analyse mislykkedes',
        'skipped_prefix' => 'AI-analyse sprunget over',
        'reason' => [
            'timeout' => 'tidsfrist udløbet',
            'authentication_failed' => 'godkendelse mislykkedes',
            'rate_limited' => 'hastighed begrænset',
            'quota_exceeded' => 'kvote overskredet',
            'unknown_error' => 'ukendt fejl',
            'output_rejected_matched_injection_marker' => 'output afvist (injection-markør)',
            'hourly_cap_reached' => 'timegrænse nået',
            'circuit_open' => 'kredsløb åbent',
        ],
    ],
    'de' => [
        'heading' => 'KI-Vorschlag',
        'footnote_prefix' => 'via',
        'disclaimer' => 'KI-generiert. Vor dem Handeln prüfen.',
        'cached_badge' => 'aus Cache',
        'failed_prefix' => 'KI-Analyse fehlgeschlagen',
        'skipped_prefix' => 'KI-Analyse übersprungen',
        'reason' => [
            'timeout' => 'Zeitüberschreitung',
            'authentication_failed' => 'Authentifizierung fehlgeschlagen',
            'rate_limited' => 'Rate begrenzt',
            'quota_exceeded' => 'Kontingent überschritten',
            'unknown_error' => 'unbekannter Fehler',
            'output_rejected_matched_injection_marker' => 'Ausgabe abgelehnt (Injection-Marker)',
            'hourly_cap_reached' => 'Stundenlimit erreicht',
            'circuit_open' => 'Stromkreis offen',
        ],
    ],
    'el' => [
        'heading' => 'Πρόταση AI',
        'footnote_prefix' => 'μέσω',
        'disclaimer' => 'Δημιουργήθηκε από AI. Επαληθεύστε πριν την εφαρμογή.',
        'cached_badge' => 'από cache',
        'failed_prefix' => 'Η ανάλυση AI απέτυχε',
        'skipped_prefix' => 'Η ανάλυση AI παραλείφθηκε',
        'reason' => [
            'timeout' => 'λήξη χρόνου',
            'authentication_failed' => 'αποτυχία ταυτοποίησης',
            'rate_limited' => 'περιορισμένος ρυθμός',
            'quota_exceeded' => 'υπέρβαση ορίου',
            'unknown_error' => 'άγνωστο σφάλμα',
            'output_rejected_matched_injection_marker' => 'απόρριψη εξόδου (δείκτης injection)',
            'hourly_cap_reached' => 'συμπληρώθηκε το ωριαίο όριο',
            'circuit_open' => 'το κύκλωμα είναι ανοιχτό',
        ],
    ],
    'es' => [
        'heading' => 'Sugerencia de IA',
        'footnote_prefix' => 'vía',
        'disclaimer' => 'Generado por IA. Verifica antes de actuar.',
        'cached_badge' => 'en caché',
        'failed_prefix' => 'Falló el análisis de IA',
        'skipped_prefix' => 'Se omitió el análisis de IA',
        'reason' => [
            'timeout' => 'tiempo agotado',
            'authentication_failed' => 'autenticación fallida',
            'rate_limited' => 'tasa limitada',
            'quota_exceeded' => 'cuota superada',
            'unknown_error' => 'error desconocido',
            'output_rejected_matched_injection_marker' => 'salida rechazada (marcador de inyección)',
            'hourly_cap_reached' => 'límite por hora alcanzado',
            'circuit_open' => 'circuito abierto',
        ],
    ],
    'fa' => [
        'heading' => 'پیشنهاد هوش مصنوعی',
        'footnote_prefix' => 'از طریق',
        'disclaimer' => 'تولید شده توسط هوش مصنوعی. قبل از اجرا تأیید کنید.',
        'cached_badge' => 'کش شده',
        'failed_prefix' => 'تحلیل هوش مصنوعی ناموفق',
        'skipped_prefix' => 'تحلیل هوش مصنوعی رد شد',
        'reason' => [
            'timeout' => 'زمان تمام شد',
            'authentication_failed' => 'احراز هویت ناموفق',
            'rate_limited' => 'نرخ محدود شده',
            'quota_exceeded' => 'سهمیه تمام شد',
            'unknown_error' => 'خطای ناشناخته',
            'output_rejected_matched_injection_marker' => 'خروجی رد شد (نشانگر تزریق)',
            'hourly_cap_reached' => 'سقف ساعتی پر شد',
            'circuit_open' => 'مدار باز است',
        ],
    ],
    'fi' => [
        'heading' => 'Tekoälyehdotus',
        'footnote_prefix' => 'lähde',
        'disclaimer' => 'Tekoälyn luoma. Tarkista ennen toimimista.',
        'cached_badge' => 'välimuistissa',
        'failed_prefix' => 'Tekoälyanalyysi epäonnistui',
        'skipped_prefix' => 'Tekoälyanalyysi ohitettiin',
        'reason' => [
            'timeout' => 'aikakatkaisu',
            'authentication_failed' => 'todennus epäonnistui',
            'rate_limited' => 'pyyntötaajuus rajoitettu',
            'quota_exceeded' => 'kiintiö ylitetty',
            'unknown_error' => 'tuntematon virhe',
            'output_rejected_matched_injection_marker' => 'tuloste hylätty (injektiomerkki)',
            'hourly_cap_reached' => 'tuntirajaan päästy',
            'circuit_open' => 'piiri auki',
        ],
    ],
    'fr' => [
        'heading' => 'Suggestion IA',
        'footnote_prefix' => 'via',
        'disclaimer' => 'Généré par IA. Vérifiez avant d\'agir.',
        'cached_badge' => 'en cache',
        'failed_prefix' => 'Échec de l\'analyse IA',
        'skipped_prefix' => 'Analyse IA ignorée',
        'reason' => [
            'timeout' => 'délai dépassé',
            'authentication_failed' => 'échec de l\'authentification',
            'rate_limited' => 'débit limité',
            'quota_exceeded' => 'quota dépassé',
            'unknown_error' => 'erreur inconnue',
            'output_rejected_matched_injection_marker' => 'sortie rejetée (marqueur d\'injection)',
            'hourly_cap_reached' => 'limite horaire atteinte',
            'circuit_open' => 'circuit ouvert',
        ],
    ],
    'he' => [
        'heading' => 'הצעת AI',
        'footnote_prefix' => 'באמצעות',
        'disclaimer' => 'נוצר על ידי AI. בדוק לפני ביצוע.',
        'cached_badge' => 'במטמון',
        'failed_prefix' => 'ניתוח ה-AI נכשל',
        'skipped_prefix' => 'ניתוח ה-AI דולג',
        'reason' => [
            'timeout' => 'תם הזמן',
            'authentication_failed' => 'אימות נכשל',
            'rate_limited' => 'קצב מוגבל',
            'quota_exceeded' => 'מכסה חרגה',
            'unknown_error' => 'שגיאה לא ידועה',
            'output_rejected_matched_injection_marker' => 'הפלט נדחה (סמן הזרקה)',
            'hourly_cap_reached' => 'הגעת למגבלה השעתית',
            'circuit_open' => 'מעגל פתוח',
        ],
    ],
    'hi' => [
        'heading' => 'AI सुझाव',
        'footnote_prefix' => 'द्वारा',
        'disclaimer' => 'AI द्वारा निर्मित। कार्रवाई से पहले सत्यापित करें।',
        'cached_badge' => 'कैश किया गया',
        'failed_prefix' => 'AI विश्लेषण विफल',
        'skipped_prefix' => 'AI विश्लेषण छोड़ा गया',
        'reason' => [
            'timeout' => 'समय समाप्त',
            'authentication_failed' => 'प्रमाणीकरण विफल',
            'rate_limited' => 'दर सीमित',
            'quota_exceeded' => 'कोटा पार',
            'unknown_error' => 'अज्ञात त्रुटि',
            'output_rejected_matched_injection_marker' => 'आउटपुट अस्वीकृत (इंजेक्शन मार्कर)',
            'hourly_cap_reached' => 'घंटा सीमा पूरी',
            'circuit_open' => 'सर्किट खुला',
        ],
    ],
    'hr' => [
        'heading' => 'AI prijedlog',
        'footnote_prefix' => 'putem',
        'disclaimer' => 'Generirano AI-jem. Provjerite prije primjene.',
        'cached_badge' => 'iz predmemorije',
        'failed_prefix' => 'AI analiza nije uspjela',
        'skipped_prefix' => 'AI analiza preskočena',
        'reason' => [
            'timeout' => 'isteklo vrijeme',
            'authentication_failed' => 'autentifikacija neuspješna',
            'rate_limited' => 'brzina ograničena',
            'quota_exceeded' => 'kvota premašena',
            'unknown_error' => 'nepoznata greška',
            'output_rejected_matched_injection_marker' => 'izlaz odbijen (oznaka injekcije)',
            'hourly_cap_reached' => 'dosegnuto satno ograničenje',
            'circuit_open' => 'krug otvoren',
        ],
    ],
    'hu' => [
        'heading' => 'AI javaslat',
        'footnote_prefix' => 'forrás',
        'disclaimer' => 'AI által generált. Művelet előtt ellenőrizze.',
        'cached_badge' => 'gyorsítótárból',
        'failed_prefix' => 'AI-elemzés sikertelen',
        'skipped_prefix' => 'AI-elemzés kihagyva',
        'reason' => [
            'timeout' => 'időtúllépés',
            'authentication_failed' => 'hitelesítés sikertelen',
            'rate_limited' => 'sebesség korlátozva',
            'quota_exceeded' => 'kvóta túllépve',
            'unknown_error' => 'ismeretlen hiba',
            'output_rejected_matched_injection_marker' => 'kimenet elutasítva (injekciós jel)',
            'hourly_cap_reached' => 'óránkénti korlát elérve',
            'circuit_open' => 'áramkör nyitva',
        ],
    ],
    'id' => [
        'heading' => 'Saran AI',
        'footnote_prefix' => 'via',
        'disclaimer' => 'Dibuat oleh AI. Periksa sebelum bertindak.',
        'cached_badge' => 'dari cache',
        'failed_prefix' => 'Analisis AI gagal',
        'skipped_prefix' => 'Analisis AI dilewati',
        'reason' => [
            'timeout' => 'waktu habis',
            'authentication_failed' => 'autentikasi gagal',
            'rate_limited' => 'laju dibatasi',
            'quota_exceeded' => 'kuota terlampaui',
            'unknown_error' => 'kesalahan tidak diketahui',
            'output_rejected_matched_injection_marker' => 'output ditolak (penanda injeksi)',
            'hourly_cap_reached' => 'batas per jam tercapai',
            'circuit_open' => 'sirkuit terbuka',
        ],
    ],
    'it' => [
        'heading' => 'Suggerimento IA',
        'footnote_prefix' => 'via',
        'disclaimer' => 'Generato dall\'IA. Verifica prima di agire.',
        'cached_badge' => 'in cache',
        'failed_prefix' => 'Analisi IA fallita',
        'skipped_prefix' => 'Analisi IA saltata',
        'reason' => [
            'timeout' => 'tempo scaduto',
            'authentication_failed' => 'autenticazione fallita',
            'rate_limited' => 'frequenza limitata',
            'quota_exceeded' => 'quota superata',
            'unknown_error' => 'errore sconosciuto',
            'output_rejected_matched_injection_marker' => 'output rifiutato (marcatore di injection)',
            'hourly_cap_reached' => 'limite orario raggiunto',
            'circuit_open' => 'circuito aperto',
        ],
    ],
    'ja' => [
        'heading' => 'AI による提案',
        'footnote_prefix' => 'via',
        'disclaimer' => 'AI 生成。実行前に確認してください。',
        'cached_badge' => 'キャッシュ済み',
        'failed_prefix' => 'AI 解析に失敗',
        'skipped_prefix' => 'AI 解析をスキップ',
        'reason' => [
            'timeout' => 'タイムアウト',
            'authentication_failed' => '認証エラー',
            'rate_limited' => 'レート制限',
            'quota_exceeded' => 'クォータ超過',
            'unknown_error' => '不明なエラー',
            'output_rejected_matched_injection_marker' => '出力を拒否（インジェクションマーカー検出）',
            'hourly_cap_reached' => '1時間あたりの上限に到達',
            'circuit_open' => 'サーキットオープン',
        ],
    ],
    'ka' => [
        'heading' => 'AI შემოთავაზება',
        'footnote_prefix' => 'მომწოდებელი',
        'disclaimer' => 'AI-ის მიერ გენერირებული. გამოყენებამდე გადაამოწმეთ.',
        'cached_badge' => 'ქეშირებული',
        'failed_prefix' => 'AI ანალიზი ჩაიშალა',
        'skipped_prefix' => 'AI ანალიზი გამოტოვებულია',
        'reason' => [
            'timeout' => 'დრო ამოიწურა',
            'authentication_failed' => 'ავტორიზაცია ჩაიშალა',
            'rate_limited' => 'სიხშირე შეზღუდულია',
            'quota_exceeded' => 'ლიმიტი ამოწურულია',
            'unknown_error' => 'უცნობი შეცდომა',
            'output_rejected_matched_injection_marker' => 'გამოსასვლელი უარყოფილია (ინექციის მარკერი)',
            'hourly_cap_reached' => 'საათობრივი ლიმიტი მიღწეულია',
            'circuit_open' => 'წრე ღიაა',
        ],
    ],
    'km' => [
        'heading' => 'ការណែនាំពី AI',
        'footnote_prefix' => 'តាមរយៈ',
        'disclaimer' => 'បង្កើតដោយ AI។ សូមផ្ទៀងផ្ទាត់មុនពេលអនុវត្ត។',
        'cached_badge' => 'ក្នុងឃ្លាំងសម្ងាត់',
        'failed_prefix' => 'ការវិភាគ AI បរាជ័យ',
        'skipped_prefix' => 'បានរំលងការវិភាគ AI',
        'reason' => [
            'timeout' => 'អស់ពេល',
            'authentication_failed' => 'ការផ្ទៀងផ្ទាត់បានបរាជ័យ',
            'rate_limited' => 'អត្រាត្រូវបានកំណត់',
            'quota_exceeded' => 'លើសកូតា',
            'unknown_error' => 'កំហុសមិនស្គាល់',
            'output_rejected_matched_injection_marker' => 'លទ្ធផលត្រូវបានបដិសេធ (សញ្ញាចាក់បញ្ចូល)',
            'hourly_cap_reached' => 'ដល់ដែនកំណត់ក្នុងមួយម៉ោង',
            'circuit_open' => 'សៀគ្វីបើកចំហ',
        ],
    ],
    'ko' => [
        'heading' => 'AI 제안',
        'footnote_prefix' => '제공',
        'disclaimer' => 'AI 생성. 실행 전 확인하세요.',
        'cached_badge' => '캐시됨',
        'failed_prefix' => 'AI 분석 실패',
        'skipped_prefix' => 'AI 분석 건너뜀',
        'reason' => [
            'timeout' => '시간 초과',
            'authentication_failed' => '인증 실패',
            'rate_limited' => '요청 제한',
            'quota_exceeded' => '할당량 초과',
            'unknown_error' => '알 수 없는 오류',
            'output_rejected_matched_injection_marker' => '출력 거부됨 (인젝션 마커)',
            'hourly_cap_reached' => '시간당 한도 도달',
            'circuit_open' => '서킷 오픈',
        ],
    ],
    'ku' => [
        'heading' => 'Pêşniyara AI',
        'footnote_prefix' => 'bi rêya',
        'disclaimer' => 'Ji aliyê AI ve hatiye çêkirin. Berî kirinê piştrast bike.',
        'cached_badge' => 'di cache de',
        'failed_prefix' => 'Analîza AI bi ser neket',
        'skipped_prefix' => 'Analîza AI hate derbaskirin',
        'reason' => [
            'timeout' => 'dem temam bû',
            'authentication_failed' => 'piştrastkirin bi ser neket',
            'rate_limited' => 'rêje sînordar e',
            'quota_exceeded' => 'kota derbas bû',
            'unknown_error' => 'çewtiya nenas',
            'output_rejected_matched_injection_marker' => 'derketin hate red kirin (nîşana injection)',
            'hourly_cap_reached' => 'sînorê demjimêrî gihîşt',
            'circuit_open' => 'çerx vekirî',
        ],
    ],
    'lt' => [
        'heading' => 'DI pasiūlymas',
        'footnote_prefix' => 'per',
        'disclaimer' => 'DI sugeneruota. Patikrinkite prieš veikdami.',
        'cached_badge' => 'iš talpyklos',
        'failed_prefix' => 'DI analizė nepavyko',
        'skipped_prefix' => 'DI analizė praleista',
        'reason' => [
            'timeout' => 'baigėsi laikas',
            'authentication_failed' => 'autentifikavimas nepavyko',
            'rate_limited' => 'dažnis ribojamas',
            'quota_exceeded' => 'kvota viršyta',
            'unknown_error' => 'nežinoma klaida',
            'output_rejected_matched_injection_marker' => 'išvestis atmesta (injekcijos žymė)',
            'hourly_cap_reached' => 'pasiekta valandos riba',
            'circuit_open' => 'grandinė atvira',
        ],
    ],
    'lus' => [
        'heading' => 'AI rawtna',
        'footnote_prefix' => 'atang',
        'disclaimer' => 'AI siam. Hman hmaa enfiah la.',
        'cached_badge' => 'cache-a awm',
        'failed_prefix' => 'AI zirchianna a hlawhtling lo',
        'skipped_prefix' => 'AI zirchianna paih a ni',
        'reason' => [
            'timeout' => 'hun a ral ta',
            'authentication_failed' => 'enchiantirna a hlawhtling lo',
            'rate_limited' => 'rate limit a awm',
            'quota_exceeded' => 'quota a chuak ta',
            'unknown_error' => 'hriat loh dik lohna',
            'output_rejected_matched_injection_marker' => 'output hnawl a ni (injection marker)',
            'hourly_cap_reached' => 'darkar tin tawpna a thleng',
            'circuit_open' => 'circuit a hawng',
        ],
    ],
    'lv' => [
        'heading' => 'MI ieteikums',
        'footnote_prefix' => 'caur',
        'disclaimer' => 'MI ģenerēts. Pārbaudiet pirms rīkošanās.',
        'cached_badge' => 'no kešatmiņas',
        'failed_prefix' => 'MI analīze neizdevās',
        'skipped_prefix' => 'MI analīze izlaista',
        'reason' => [
            'timeout' => 'laiks beidzies',
            'authentication_failed' => 'autentifikācija neizdevās',
            'rate_limited' => 'biežums ierobežots',
            'quota_exceeded' => 'kvota pārsniegta',
            'unknown_error' => 'nezināma kļūda',
            'output_rejected_matched_injection_marker' => 'izvade noraidīta (injekcijas marķieris)',
            'hourly_cap_reached' => 'sasniegts stundas limits',
            'circuit_open' => 'ķēde atvērta',
        ],
    ],
    'mk' => [
        'heading' => 'AI предлог',
        'footnote_prefix' => 'преку',
        'disclaimer' => 'Генерирано од AI. Проверете пред да дејствувате.',
        'cached_badge' => 'кеширано',
        'failed_prefix' => 'AI анализата не успеа',
        'skipped_prefix' => 'AI анализата е прескокната',
        'reason' => [
            'timeout' => 'времето истече',
            'authentication_failed' => 'неуспешна автентикација',
            'rate_limited' => 'ограничена брзина',
            'quota_exceeded' => 'надмината квота',
            'unknown_error' => 'непозната грешка',
            'output_rejected_matched_injection_marker' => 'излезот е одбиен (маркер за инјекција)',
            'hourly_cap_reached' => 'достигнат часовен лимит',
            'circuit_open' => 'колото е отворено',
        ],
    ],
    'mn' => [
        'heading' => 'AI санал',
        'footnote_prefix' => 'эх сурвалж',
        'disclaimer' => 'AI үүсгэсэн. Гүйцэтгэхийн өмнө шалгана уу.',
        'cached_badge' => 'кэшлэгдсэн',
        'failed_prefix' => 'AI шинжилгээ амжилтгүй',
        'skipped_prefix' => 'AI шинжилгээг алгассан',
        'reason' => [
            'timeout' => 'хугацаа дууссан',
            'authentication_failed' => 'баталгаажуулалт амжилтгүй',
            'rate_limited' => 'хязгаарлагдсан хурд',
            'quota_exceeded' => 'квот хэтэрсэн',
            'unknown_error' => 'тодорхойгүй алдаа',
            'output_rejected_matched_injection_marker' => 'үр дүнг татгалзсан (тарих тэмдэглэгээ)',
            'hourly_cap_reached' => 'цагийн хязгаарт хүрсэн',
            'circuit_open' => 'хэлхээ нээлттэй',
        ],
    ],
    'ms' => [
        'heading' => 'Cadangan AI',
        'footnote_prefix' => 'melalui',
        'disclaimer' => 'Dijana oleh AI. Sahkan sebelum bertindak.',
        'cached_badge' => 'dari cache',
        'failed_prefix' => 'Analisis AI gagal',
        'skipped_prefix' => 'Analisis AI dilangkau',
        'reason' => [
            'timeout' => 'masa tamat',
            'authentication_failed' => 'pengesahan gagal',
            'rate_limited' => 'kadar dihadkan',
            'quota_exceeded' => 'kuota terlampau',
            'unknown_error' => 'ralat tidak diketahui',
            'output_rejected_matched_injection_marker' => 'output ditolak (penanda injection)',
            'hourly_cap_reached' => 'had sejam dicapai',
            'circuit_open' => 'litar terbuka',
        ],
    ],
    'my' => [
        'heading' => 'AI အကြံပြုချက်',
        'footnote_prefix' => 'မှ',
        'disclaimer' => 'AI ဖြင့်ထုတ်လုပ်ထားသည်။ မလုပ်မီ စစ်ဆေးပါ။',
        'cached_badge' => 'cache တွင်',
        'failed_prefix' => 'AI ခွဲခြမ်းစိတ်ဖြာခြင်း မအောင်မြင်ပါ',
        'skipped_prefix' => 'AI ခွဲခြမ်းစိတ်ဖြာခြင်း ကျော်သွားသည်',
        'reason' => [
            'timeout' => 'အချိန်ကုန်ပြီ',
            'authentication_failed' => 'အထောက်အထား စိစစ်ခြင်း မအောင်မြင်ပါ',
            'rate_limited' => 'နှုန်းကန့်သတ်ထားသည်',
            'quota_exceeded' => 'ကိုတာ ကျော်လွန်သွားပြီ',
            'unknown_error' => 'အမည်မသိ အမှား',
            'output_rejected_matched_injection_marker' => 'ထုတ်လွှတ်ချက် ပယ်ချ (injection အမှတ်အသား)',
            'hourly_cap_reached' => 'တစ်နာရီ ကန့်သတ်ချက်သို့ ရောက်ရှိသည်',
            'circuit_open' => 'circuit ဖွင့်ထား',
        ],
    ],
    'nb' => [
        'heading' => 'KI-forslag',
        'footnote_prefix' => 'via',
        'disclaimer' => 'Generert av KI. Verifiser før du handler.',
        'cached_badge' => 'fra cache',
        'failed_prefix' => 'KI-analyse mislyktes',
        'skipped_prefix' => 'KI-analyse hoppet over',
        'reason' => [
            'timeout' => 'tidsavbrudd',
            'authentication_failed' => 'autentisering mislyktes',
            'rate_limited' => 'frekvens begrenset',
            'quota_exceeded' => 'kvote overskredet',
            'unknown_error' => 'ukjent feil',
            'output_rejected_matched_injection_marker' => 'utdata avvist (injection-markør)',
            'hourly_cap_reached' => 'timegrense nådd',
            'circuit_open' => 'krets åpen',
        ],
    ],
    'ne' => [
        'heading' => 'AI सुझाव',
        'footnote_prefix' => 'मार्फत',
        'disclaimer' => 'AI द्वारा निर्मित। काम गर्नु अघि प्रमाणित गर्नुहोस्।',
        'cached_badge' => 'क्यास गरिएको',
        'failed_prefix' => 'AI विश्लेषण असफल',
        'skipped_prefix' => 'AI विश्लेषण छोडियो',
        'reason' => [
            'timeout' => 'समय सकियो',
            'authentication_failed' => 'प्रमाणीकरण असफल',
            'rate_limited' => 'दर सीमित',
            'quota_exceeded' => 'कोटा सकियो',
            'unknown_error' => 'अज्ञात त्रुटि',
            'output_rejected_matched_injection_marker' => 'आउटपुट अस्वीकृत (इन्जेक्शन मार्कर)',
            'hourly_cap_reached' => 'घन्टाको सीमा पुग्यो',
            'circuit_open' => 'सर्किट खुला',
        ],
    ],
    'nl' => [
        'heading' => 'AI-suggestie',
        'footnote_prefix' => 'via',
        'disclaimer' => 'AI-gegenereerd. Controleer voor gebruik.',
        'cached_badge' => 'uit cache',
        'failed_prefix' => 'AI-analyse mislukt',
        'skipped_prefix' => 'AI-analyse overgeslagen',
        'reason' => [
            'timeout' => 'time-out',
            'authentication_failed' => 'authenticatie mislukt',
            'rate_limited' => 'snelheid beperkt',
            'quota_exceeded' => 'quotum overschreden',
            'unknown_error' => 'onbekende fout',
            'output_rejected_matched_injection_marker' => 'uitvoer geweigerd (injectie-markering)',
            'hourly_cap_reached' => 'uurlimiet bereikt',
            'circuit_open' => 'circuit open',
        ],
    ],
    'pl' => [
        'heading' => 'Sugestia AI',
        'footnote_prefix' => 'przez',
        'disclaimer' => 'Wygenerowano przez AI. Zweryfikuj przed użyciem.',
        'cached_badge' => 'z pamięci podręcznej',
        'failed_prefix' => 'Analiza AI nie powiodła się',
        'skipped_prefix' => 'Analiza AI pominięta',
        'reason' => [
            'timeout' => 'przekroczono czas',
            'authentication_failed' => 'uwierzytelnianie nie powiodło się',
            'rate_limited' => 'ograniczona częstotliwość',
            'quota_exceeded' => 'przekroczono limit',
            'unknown_error' => 'nieznany błąd',
            'output_rejected_matched_injection_marker' => 'wyjście odrzucone (znacznik injection)',
            'hourly_cap_reached' => 'osiągnięto limit godzinowy',
            'circuit_open' => 'obwód otwarty',
        ],
    ],
    'pt' => [
        'heading' => 'Sugestão da IA',
        'footnote_prefix' => 'via',
        'disclaimer' => 'Gerado por IA. Verifique antes de agir.',
        'cached_badge' => 'em cache',
        'failed_prefix' => 'Análise de IA falhou',
        'skipped_prefix' => 'Análise de IA ignorada',
        'reason' => [
            'timeout' => 'tempo esgotado',
            'authentication_failed' => 'falha na autenticação',
            'rate_limited' => 'taxa limitada',
            'quota_exceeded' => 'quota excedida',
            'unknown_error' => 'erro desconhecido',
            'output_rejected_matched_injection_marker' => 'saída rejeitada (marcador de injeção)',
            'hourly_cap_reached' => 'limite horário atingido',
            'circuit_open' => 'circuito aberto',
        ],
    ],
    'pt_BR' => [
        'heading' => 'Sugestão da IA',
        'footnote_prefix' => 'via',
        'disclaimer' => 'Gerado por IA. Verifique antes de agir.',
        'cached_badge' => 'em cache',
        'failed_prefix' => 'Análise de IA falhou',
        'skipped_prefix' => 'Análise de IA ignorada',
        'reason' => [
            'timeout' => 'tempo esgotado',
            'authentication_failed' => 'falha na autenticação',
            'rate_limited' => 'taxa limitada',
            'quota_exceeded' => 'cota excedida',
            'unknown_error' => 'erro desconhecido',
            'output_rejected_matched_injection_marker' => 'saída rejeitada (marcador de injeção)',
            'hourly_cap_reached' => 'limite por hora atingido',
            'circuit_open' => 'circuito aberto',
        ],
    ],
    'ro' => [
        'heading' => 'Sugestie AI',
        'footnote_prefix' => 'prin',
        'disclaimer' => 'Generat de AI. Verificați înainte de a acționa.',
        'cached_badge' => 'din cache',
        'failed_prefix' => 'Analiza AI a eșuat',
        'skipped_prefix' => 'Analiza AI a fost omisă',
        'reason' => [
            'timeout' => 'timp expirat',
            'authentication_failed' => 'autentificare eșuată',
            'rate_limited' => 'rată limitată',
            'quota_exceeded' => 'cotă depășită',
            'unknown_error' => 'eroare necunoscută',
            'output_rejected_matched_injection_marker' => 'ieșire respinsă (marcaj de injection)',
            'hourly_cap_reached' => 'limită orară atinsă',
            'circuit_open' => 'circuit deschis',
        ],
    ],
    'ru' => [
        'heading' => 'Предложение ИИ',
        'footnote_prefix' => 'через',
        'disclaimer' => 'Сгенерировано ИИ. Проверьте перед применением.',
        'cached_badge' => 'из кэша',
        'failed_prefix' => 'Анализ ИИ не удался',
        'skipped_prefix' => 'Анализ ИИ пропущен',
        'reason' => [
            'timeout' => 'тайм-аут',
            'authentication_failed' => 'ошибка аутентификации',
            'rate_limited' => 'частота ограничена',
            'quota_exceeded' => 'квота исчерпана',
            'unknown_error' => 'неизвестная ошибка',
            'output_rejected_matched_injection_marker' => 'вывод отклонён (маркер инъекции)',
            'hourly_cap_reached' => 'достигнут часовой лимит',
            'circuit_open' => 'цепь разомкнута',
        ],
    ],
    'sk' => [
        'heading' => 'Návrh AI',
        'footnote_prefix' => 'cez',
        'disclaimer' => 'Vygenerované AI. Pred použitím overte.',
        'cached_badge' => 'z cache',
        'failed_prefix' => 'Analýza AI zlyhala',
        'skipped_prefix' => 'Analýza AI preskočená',
        'reason' => [
            'timeout' => 'vypršal časový limit',
            'authentication_failed' => 'overenie zlyhalo',
            'rate_limited' => 'frekvencia obmedzená',
            'quota_exceeded' => 'kvóta prekročená',
            'unknown_error' => 'neznáma chyba',
            'output_rejected_matched_injection_marker' => 'výstup zamietnutý (značka injekcie)',
            'hourly_cap_reached' => 'hodinový limit dosiahnutý',
            'circuit_open' => 'okruh otvorený',
        ],
    ],
    'sl' => [
        'heading' => 'Predlog UI',
        'footnote_prefix' => 'preko',
        'disclaimer' => 'Generirano z UI. Pred uporabo preverite.',
        'cached_badge' => 'iz predpomnilnika',
        'failed_prefix' => 'Analiza UI ni uspela',
        'skipped_prefix' => 'Analiza UI preskočena',
        'reason' => [
            'timeout' => 'čas potekel',
            'authentication_failed' => 'overjanje ni uspelo',
            'rate_limited' => 'hitrost omejena',
            'quota_exceeded' => 'kvota presežena',
            'unknown_error' => 'neznana napaka',
            'output_rejected_matched_injection_marker' => 'izhod zavrnjen (oznaka injekcije)',
            'hourly_cap_reached' => 'urna omejitev dosežena',
            'circuit_open' => 'tokokrog odprt',
        ],
    ],
    'sq' => [
        'heading' => 'Sugjerim i IA',
        'footnote_prefix' => 'përmes',
        'disclaimer' => 'Gjeneruar nga IA. Verifikoni përpara veprimit.',
        'cached_badge' => 'i ruajtur',
        'failed_prefix' => 'Analiza e IA dështoi',
        'skipped_prefix' => 'Analiza e IA u anashkalua',
        'reason' => [
            'timeout' => 'koha skadoi',
            'authentication_failed' => 'vërtetimi dështoi',
            'rate_limited' => 'shpejtësi e kufizuar',
            'quota_exceeded' => 'kuota u tejkalua',
            'unknown_error' => 'gabim i panjohur',
            'output_rejected_matched_injection_marker' => 'dalja u refuzua (shenjë injection)',
            'hourly_cap_reached' => 'kufiri orar u arrit',
            'circuit_open' => 'qarku është i hapur',
        ],
    ],
    'sr_Cyrl' => [
        'heading' => 'AI предлог',
        'footnote_prefix' => 'преко',
        'disclaimer' => 'Генерисано од AI. Проверите пре примене.',
        'cached_badge' => 'из кеша',
        'failed_prefix' => 'AI анализа није успела',
        'skipped_prefix' => 'AI анализа је прескочена',
        'reason' => [
            'timeout' => 'време истекло',
            'authentication_failed' => 'аутентикација није успела',
            'rate_limited' => 'брзина ограничена',
            'quota_exceeded' => 'квота прекорачена',
            'unknown_error' => 'непозната грешка',
            'output_rejected_matched_injection_marker' => 'излаз одбачен (ознака инјекције)',
            'hourly_cap_reached' => 'достигнут сатни лимит',
            'circuit_open' => 'коло отворено',
        ],
    ],
    'sr_Latn' => [
        'heading' => 'AI predlog',
        'footnote_prefix' => 'preko',
        'disclaimer' => 'Generisano od AI. Proverite pre primene.',
        'cached_badge' => 'iz keša',
        'failed_prefix' => 'AI analiza nije uspela',
        'skipped_prefix' => 'AI analiza je preskočena',
        'reason' => [
            'timeout' => 'vreme isteklo',
            'authentication_failed' => 'autentikacija nije uspela',
            'rate_limited' => 'brzina ograničena',
            'quota_exceeded' => 'kvota prekoračena',
            'unknown_error' => 'nepoznata greška',
            'output_rejected_matched_injection_marker' => 'izlaz odbačen (oznaka injekcije)',
            'hourly_cap_reached' => 'dostignut satni limit',
            'circuit_open' => 'kolo otvoreno',
        ],
    ],
    'sv' => [
        'heading' => 'AI-förslag',
        'footnote_prefix' => 'via',
        'disclaimer' => 'AI-genererat. Verifiera innan du agerar.',
        'cached_badge' => 'från cache',
        'failed_prefix' => 'AI-analys misslyckades',
        'skipped_prefix' => 'AI-analys hoppades över',
        'reason' => [
            'timeout' => 'tidsgräns uppnådd',
            'authentication_failed' => 'autentisering misslyckades',
            'rate_limited' => 'hastighet begränsad',
            'quota_exceeded' => 'kvot överskriden',
            'unknown_error' => 'okänt fel',
            'output_rejected_matched_injection_marker' => 'utdata avvisad (injection-markör)',
            'hourly_cap_reached' => 'timgräns uppnådd',
            'circuit_open' => 'kretsen öppen',
        ],
    ],
    'sw' => [
        'heading' => 'Pendekezo la AI',
        'footnote_prefix' => 'kupitia',
        'disclaimer' => 'Imezalishwa na AI. Hakiki kabla ya kutekeleza.',
        'cached_badge' => 'iliyohifadhiwa',
        'failed_prefix' => 'Uchanganuzi wa AI umeshindwa',
        'skipped_prefix' => 'Uchanganuzi wa AI umerukwa',
        'reason' => [
            'timeout' => 'muda umeisha',
            'authentication_failed' => 'uthibitishaji umeshindwa',
            'rate_limited' => 'kasi imepunguzwa',
            'quota_exceeded' => 'mgao umezidiwa',
            'unknown_error' => 'hitilafu isiyojulikana',
            'output_rejected_matched_injection_marker' => 'matokeo yamekataliwa (alama ya kuingiza)',
            'hourly_cap_reached' => 'kikomo cha saa kimefikiwa',
            'circuit_open' => 'mzunguko umefunguliwa',
        ],
    ],
    'th' => [
        'heading' => 'คำแนะนำจาก AI',
        'footnote_prefix' => 'ผ่าน',
        'disclaimer' => 'สร้างโดย AI ตรวจสอบก่อนใช้งาน',
        'cached_badge' => 'แคช',
        'failed_prefix' => 'การวิเคราะห์ AI ล้มเหลว',
        'skipped_prefix' => 'ข้ามการวิเคราะห์ AI',
        'reason' => [
            'timeout' => 'หมดเวลา',
            'authentication_failed' => 'การยืนยันตัวตนล้มเหลว',
            'rate_limited' => 'จำกัดอัตรา',
            'quota_exceeded' => 'เกินโควตา',
            'unknown_error' => 'ข้อผิดพลาดที่ไม่รู้จัก',
            'output_rejected_matched_injection_marker' => 'ผลลัพธ์ถูกปฏิเสธ (เครื่องหมาย injection)',
            'hourly_cap_reached' => 'ถึงขีดจำกัดต่อชั่วโมง',
            'circuit_open' => 'เซอร์กิตเปิด',
        ],
    ],
    'tr' => [
        'heading' => 'AI Önerisi',
        'footnote_prefix' => 'üzerinden',
        'disclaimer' => 'AI tarafından oluşturuldu. Uygulamadan önce doğrulayın.',
        'cached_badge' => 'önbellekte',
        'failed_prefix' => 'AI analizi başarısız',
        'skipped_prefix' => 'AI analizi atlandı',
        'reason' => [
            'timeout' => 'zaman aşımı',
            'authentication_failed' => 'kimlik doğrulama başarısız',
            'rate_limited' => 'hız sınırlandı',
            'quota_exceeded' => 'kota aşıldı',
            'unknown_error' => 'bilinmeyen hata',
            'output_rejected_matched_injection_marker' => 'çıktı reddedildi (injection işareti)',
            'hourly_cap_reached' => 'saatlik sınıra ulaşıldı',
            'circuit_open' => 'devre açık',
        ],
    ],
    'uk' => [
        'heading' => 'Пропозиція ШІ',
        'footnote_prefix' => 'через',
        'disclaimer' => 'Згенеровано ШІ. Перевірте перед застосуванням.',
        'cached_badge' => 'з кешу',
        'failed_prefix' => 'Аналіз ШІ не вдався',
        'skipped_prefix' => 'Аналіз ШІ пропущено',
        'reason' => [
            'timeout' => 'час очікування вичерпано',
            'authentication_failed' => 'помилка автентифікації',
            'rate_limited' => 'обмежена частота',
            'quota_exceeded' => 'квоту перевищено',
            'unknown_error' => 'невідома помилка',
            'output_rejected_matched_injection_marker' => 'вивід відхилено (маркер ін\'єкції)',
            'hourly_cap_reached' => 'досягнуто погодинного ліміту',
            'circuit_open' => 'коло розімкнуто',
        ],
    ],
    'ur' => [
        'heading' => 'AI تجویز',
        'footnote_prefix' => 'بذریعہ',
        'disclaimer' => 'AI سے تیار شدہ۔ عمل سے پہلے تصدیق کریں۔',
        'cached_badge' => 'کیش شدہ',
        'failed_prefix' => 'AI تجزیہ ناکام',
        'skipped_prefix' => 'AI تجزیہ چھوڑ دیا گیا',
        'reason' => [
            'timeout' => 'وقت ختم',
            'authentication_failed' => 'تصدیق ناکام',
            'rate_limited' => 'شرح محدود',
            'quota_exceeded' => 'کوٹا ختم',
            'unknown_error' => 'نامعلوم خرابی',
            'output_rejected_matched_injection_marker' => 'آؤٹ پٹ مسترد (انجیکشن مارکر)',
            'hourly_cap_reached' => 'فی گھنٹہ حد پوری',
            'circuit_open' => 'سرکٹ کھلا',
        ],
    ],
    'uz' => [
        'heading' => 'AI taklifi',
        'footnote_prefix' => 'orqali',
        'disclaimer' => 'AI tomonidan yaratilgan. Bajarishdan oldin tekshiring.',
        'cached_badge' => 'keshlangan',
        'failed_prefix' => 'AI tahlili muvaffaqiyatsiz',
        'skipped_prefix' => 'AI tahlili o\'tkazib yuborildi',
        'reason' => [
            'timeout' => 'vaqt tugadi',
            'authentication_failed' => 'autentifikatsiya muvaffaqiyatsiz',
            'rate_limited' => 'tezlik cheklangan',
            'quota_exceeded' => 'kvota oshib ketdi',
            'unknown_error' => 'noma\'lum xato',
            'output_rejected_matched_injection_marker' => 'chiqish rad etildi (injection belgisi)',
            'hourly_cap_reached' => 'soatlik chegaraga yetildi',
            'circuit_open' => 'davra ochiq',
        ],
    ],
    'vi' => [
        'heading' => 'Gợi ý AI',
        'footnote_prefix' => 'qua',
        'disclaimer' => 'Do AI tạo. Xác minh trước khi thực hiện.',
        'cached_badge' => 'từ cache',
        'failed_prefix' => 'Phân tích AI thất bại',
        'skipped_prefix' => 'Đã bỏ qua phân tích AI',
        'reason' => [
            'timeout' => 'hết thời gian',
            'authentication_failed' => 'xác thực thất bại',
            'rate_limited' => 'giới hạn tốc độ',
            'quota_exceeded' => 'vượt hạn ngạch',
            'unknown_error' => 'lỗi không xác định',
            'output_rejected_matched_injection_marker' => 'đầu ra bị từ chối (dấu hiệu injection)',
            'hourly_cap_reached' => 'đã đạt giới hạn theo giờ',
            'circuit_open' => 'mạch hở',
        ],
    ],
    'zh_CN' => [
        'heading' => 'AI 建议',
        'footnote_prefix' => '来自',
        'disclaimer' => 'AI 生成。执行前请核实。',
        'cached_badge' => '已缓存',
        'failed_prefix' => 'AI 分析失败',
        'skipped_prefix' => '已跳过 AI 分析',
        'reason' => [
            'timeout' => '超时',
            'authentication_failed' => '认证失败',
            'rate_limited' => '速率受限',
            'quota_exceeded' => '配额已用完',
            'unknown_error' => '未知错误',
            'output_rejected_matched_injection_marker' => '输出被拒绝（注入标记）',
            'hourly_cap_reached' => '已达每小时上限',
            'circuit_open' => '熔断器已开启',
        ],
    ],
    'zh_HK' => [
        'heading' => 'AI 建議',
        'footnote_prefix' => '來自',
        'disclaimer' => 'AI 生成。執行前請核實。',
        'cached_badge' => '已快取',
        'failed_prefix' => 'AI 分析失敗',
        'skipped_prefix' => '已略過 AI 分析',
        'reason' => [
            'timeout' => '逾時',
            'authentication_failed' => '驗證失敗',
            'rate_limited' => '速率受限',
            'quota_exceeded' => '配額已用完',
            'unknown_error' => '未知錯誤',
            'output_rejected_matched_injection_marker' => '輸出被拒絕（注入標記）',
            'hourly_cap_reached' => '已達每小時上限',
            'circuit_open' => '熔斷器已開啟',
        ],
    ],
    'zh_TW' => [
        'heading' => 'AI 建議',
        'footnote_prefix' => '來自',
        'disclaimer' => 'AI 生成。執行前請核實。',
        'cached_badge' => '已快取',
        'failed_prefix' => 'AI 分析失敗',
        'skipped_prefix' => '已略過 AI 分析',
        'reason' => [
            'timeout' => '逾時',
            'authentication_failed' => '驗證失敗',
            'rate_limited' => '速率受限',
            'quota_exceeded' => '配額已用完',
            'unknown_error' => '未知錯誤',
            'output_rejected_matched_injection_marker' => '輸出已拒絕（注入標記）',
            'hourly_cap_reached' => '已達每小時上限',
            'circuit_open' => '熔斷器已開啟',
        ],
    ],
];

$langDir = __DIR__.'/../resources/lang';

$wrote = 0;
$skipped = 0;

foreach ($translations as $locale => $aiBlock) {
    $file = "{$langDir}/{$locale}/fin-sentinel.php";
    if (! is_file($file)) {
        echo "SKIP missing: {$file}\n";
        $skipped++;

        continue;
    }

    $existing = require $file;

    if (! is_array($existing) || ! isset($existing['email']) || ! is_array($existing['email'])) {
        echo "SKIP malformed: {$file}\n";
        $skipped++;

        continue;
    }

    $existing['email']['ai'] = $aiBlock;

    $php = "<?php\n\ndeclare(strict_types=1);\n\nreturn ".var_export_short($existing, 0).";\n";
    file_put_contents($file, $php);
    echo "WROTE: {$file}\n";
    $wrote++;
}

echo "\nDone: {$wrote} written, {$skipped} skipped.\n";

function var_export_short(mixed $value, int $indent): string
{
    if (is_array($value)) {
        if ($value === []) {
            return '[]';
        }

        $isList = array_is_list($value);
        $pad = str_repeat('    ', $indent);
        $padInner = str_repeat('    ', $indent + 1);
        $parts = [];

        foreach ($value as $k => $v) {
            $key = $isList
                ? ''
                : (is_int($k) ? $k.' => ' : "'".addcslashes((string) $k, "'\\")."' => ");
            $parts[] = $padInner.$key.var_export_short($v, $indent + 1);
        }

        return "[\n".implode(",\n", $parts).",\n".$pad.']';
    }

    if (is_string($value)) {
        return "'".addcslashes($value, "'\\")."'";
    }

    if (is_bool($value)) {
        return $value ? 'true' : 'false';
    }

    if ($value === null) {
        return 'null';
    }

    return var_export($value, true);
}
